/// <reference types="vite/client" />
/// <reference types="@vue-macros/reactivity-transform/macros-global" />


// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
    // ... could include environment variables

    /** Stripe API Key */
    readonly VITE_STRIPE_API_KEY: string;
}

interface ImportMeta {
    readonly env: ImportMetaEnv;
}

// vite-env.d.ts
declare const __APP_VERSION__: string
